store:
  image:
    registry: ""
    repository: atomix/atomix-raft-storage-node
    tag: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicas: 1
  partitions: 1
  raft: {}
  persistence:
    storageClass: ""
    storageSize: 1Gi
