apiVersion: cloud.atomix.io/v1beta1
kind: Database
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusters: {{ .Values.clusters }}
  template:
    spec:
      partitions: {{ .Values.partitions }}
      backend:
        image: {{ .Values.backend.image }}
        replicas: {{ .Values.backend.replicas }}
